dataset1:
  dirpaths: [/Users/luke/skywalk/local-data,]
  users: [tylerchen, jackieyang, selenasun,]
  datacollector_versions: [guitar_hero_tap_hold,]
  firmware_versions: [v0.0, v0.1,]
  trial_types: [1, 4, 5]
  dates: ['2022-03-06', '2022-03-18',]
  hands: [right, left]
  exclude_files: [
    2022-03-18T13-56-01_guitarhero_tylerchen_easy_1gestures,
    2022-07-02T19-23-55_guitarhero_tylerchen_easy_1gestures
  ]
  
