hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - model: skywalkcnnv1
  - data: 
    - tyler
  - dataset: dataset
  - dataloader: dataloader

deterministic: true
dev_run: false
progress_bar: true
resume_training: false
print_summary: true
detect_anomaly: true
val_freq: 1
